[static_template_values]
monitor_settings = "monitor=DP-1,3440x1440@174.96201,1586x-100,1.00000000,transform,0,vrr,0"
laptop_settings = "monitor=eDP-1,1920x1200@60.00100,5076x90,1.25000000,transform,0,vrr,0"
laptop_disabled = "monitor=eDP-1,disable"

[profiles.laptop-only-open]
config_file = "/home/danny/.config/hyprdynamicmonitors/hyprconfigs/laptop-only-open.go.tmpl"

[profiles.laptop-only-open.conditions]
lid_state = "Opened"

[[profiles.laptop-only-open.conditions.required_monitors]]
name = "eDP-1"

[profiles.docked-laptop-open]
config_file = "/home/danny/.config/hyprdynamicmonitors/hyprconfigs/docked-laptop-open.go.tmpl"
config_file_type = "template"

[profiles.docked-laptop-open.conditons]
lid_state = "Opened"

[[profiles.docked-laptop-open.conditions.required_monitors]]
name = "eDP-1"

[[profiles.docked-laptop-open.conditions.required_monitors]]
name = "DP-1"

[profiles.docked-laptop-closed]
config_file = "/home/danny/.config/hyprdynamicmonitors/hyprconfigs/docked-laptop-closed.go.tmpl"
config_file_type = "template"

[profiles.docked-laptop-closed.conditions]
lid_state = "Closed"

[[profiles.docked-laptop-closed.conditions.required_monitors]]
name = "DP-1"

